// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.region.update.updated", 1766553189);
user_pref("browser.search.region", "LK");
user_pref("calendar.caldav.googleResync", 1766553186);
user_pref("calendar.list.sortOrder", "4b87a7f5-c0a5-4e6b-9c34-eb72e52e804b");
user_pref("calendar.registry.4b87a7f5-c0a5-4e6b-9c34-eb72e52e804b.calendar-main-default", true);
user_pref("calendar.registry.4b87a7f5-c0a5-4e6b-9c34-eb72e52e804b.calendar-main-in-composite", true);
user_pref("calendar.registry.4b87a7f5-c0a5-4e6b-9c34-eb72e52e804b.disabled", true);
user_pref("calendar.registry.4b87a7f5-c0a5-4e6b-9c34-eb72e52e804b.name", "Home");
user_pref("calendar.registry.4b87a7f5-c0a5-4e6b-9c34-eb72e52e804b.type", "storage");
user_pref("calendar.registry.4b87a7f5-c0a5-4e6b-9c34-eb72e52e804b.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Asia/Colombo");
user_pref("calendar.timezone.useSystemTimezone", true);
user_pref("calendar.ui.version", 3);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 36);
user_pref("extensions.getAddons.cache.lastUpdate", 1766553178);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.hasExperimentsInstalled", false);
user_pref("extensions.hasExtensionsInstalled", false);
user_pref("extensions.lastAppBuildId", "20250627203320");
user_pref("extensions.lastAppVersion", "128.12.0");
user_pref("extensions.lastPlatformVersion", "128.12.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"94424c7e-9453-40a4-abb8-eef96085b813\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("mail.ui-rdf.version", 46);
user_pref("mailnews.database.global.datastore.id", "3b31c3d5-b795-4676-857d-152f33f8599");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "128.12.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("toolkit.startup.last_success", 1766553163);
user_pref("toolkit.telemetry.cachedClientID", "c95a1c9f-3272-4fa3-a9c7-9345850bbb2e");
user_pref("toolkit.telemetry.previousBuildID", "20250627203320");
